[2024-07-24T19:50:59.230+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T19:50:59.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline manual__2024-07-24T19:49:50.613864+00:00 [queued]>
[2024-07-24T19:50:59.263+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline manual__2024-07-24T19:49:50.613864+00:00 [queued]>
[2024-07-24T19:50:59.263+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-24T19:50:59.277+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2024-07-24 19:49:50.613864+00:00
[2024-07-24T19:50:59.284+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=414) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T19:50:59.286+0000] {standard_task_runner.py:63} INFO - Started process 423 to run task
[2024-07-24T19:50:59.286+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'manual__2024-07-24T19:49:50.613864+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpqhs38ho1']
[2024-07-24T19:50:59.287+0000] {standard_task_runner.py:91} INFO - Job 153: Subtask pipeline
[2024-07-24T19:50:59.332+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline manual__2024-07-24T19:49:50.613864+00:00 [running]> on host f7e8a3dbc720
[2024-07-24T19:50:59.420+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T19:49:50.613864+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T19:49:50.613864+00:00'
[2024-07-24T19:50:59.421+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T19:50:59.424+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T19:50:59.425+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/pipeline.py", line 70, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/airflow_hw/data/train/homework.csv'
[2024-07-24T19:50:59.438+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=pipeline, run_id=manual__2024-07-24T19:49:50.613864+00:00, execution_date=20240724T194950, start_date=20240724T195059, end_date=20240724T195059
[2024-07-24T19:50:59.452+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 153 for task pipeline ([Errno 2] No such file or directory: '/home/airflow/airflow_hw/data/train/homework.csv'; 423)
[2024-07-24T19:50:59.500+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-24T19:50:59.511+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
