[2024-07-24T11:12:17.705+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T11:12:17.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline manual__2024-07-24T11:11:09.194549+00:00 [queued]>
[2024-07-24T11:12:17.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline manual__2024-07-24T11:11:09.194549+00:00 [queued]>
[2024-07-24T11:12:17.736+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-24T11:12:17.751+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2024-07-24 11:11:09.194549+00:00
[2024-07-24T11:12:17.757+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T11:12:17.759+0000] {standard_task_runner.py:63} INFO - Started process 1139 to run task
[2024-07-24T11:12:17.759+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'manual__2024-07-24T11:11:09.194549+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmptknzlbn7']
[2024-07-24T11:12:17.761+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask pipeline
[2024-07-24T11:12:17.805+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline manual__2024-07-24T11:11:09.194549+00:00 [running]> on host f7e8a3dbc720
[2024-07-24T11:12:17.889+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T11:11:09.194549+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T11:11:09.194549+00:00'
[2024-07-24T11:12:17.891+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T11:12:17.893+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T11:12:17.894+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/modules/pipeline.py", line 70, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/airflow_hw/data/train/homework.csv'
[2024-07-24T11:12:17.907+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=pipeline, run_id=manual__2024-07-24T11:11:09.194549+00:00, execution_date=20240724T111109, start_date=20240724T111217, end_date=20240724T111217
[2024-07-24T11:12:17.919+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task pipeline ([Errno 2] No such file or directory: '/home/airflow/airflow_hw/data/train/homework.csv'; 1139)
[2024-07-24T11:12:17.933+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-24T11:12:17.957+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T11:12:17.962+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
